import js from "@eslint/js";
import tseslint from "typescript-eslint";
import importX from "eslint-plugin-import-x";
import compat from "eslint-plugin-compat";

const browserGlobals = {
  window: "readonly",
  document: "readonly",
  navigator: "readonly",
  localStorage: "readonly",
  fetch: "readonly",
  AbortController: "readonly",
  AbortSignal: "readonly",
  setTimeout: "readonly",
  clearTimeout: "readonly",
  setInterval: "readonly",
  clearInterval: "readonly",
  requestAnimationFrame: "readonly",
  requestIdleCallback: "readonly",
  console: "readonly",
  getComputedStyle: "readonly",
  Map: "readonly",
  Set: "readonly",
  Promise: "readonly",
  URLSearchParams: "readonly",
  URL: "readonly",
  Intl: "readonly",
  performance: "readonly",
  HTMLElement: "readonly",
  HTMLSelectElement: "readonly",
  KeyboardEvent: "readonly",
  Event: "readonly",
  CustomEvent: "readonly",
  DOMParser: "readonly",
  location: "readonly",
  history: "readonly",
  Blob: "readonly",
  alert: "readonly",
  prompt: "readonly",
  Notification: "readonly",
  CSS: "readonly",
  MutationObserver: "readonly",
  ResizeObserver: "readonly",
  IntersectionObserver: "readonly",
  PushManager: "readonly",
  ServiceWorkerRegistration: "readonly",
  structuredClone: "readonly",
  queueMicrotask: "readonly",
  crypto: "readonly",
};

const sharedRules = {
  "no-eval": "error",
  "no-implied-eval": "error",
  "no-new-func": "error",
  "no-dupe-args": "error",
  "no-dupe-keys": "error",
  "no-duplicate-case": "error",
  "no-unreachable": "error",
  "use-isnan": "error",
  "valid-typeof": "error",
  "no-constant-condition": ["error", { checkLoops: false }],
  eqeqeq: ["error", "smart"],
  "no-var": "error",
  "no-redeclare": "error",
  "no-empty": ["error", { allowEmptyCatch: true }],
  "no-debugger": "error",
  "no-sparse-arrays": "error",
  "no-template-curly-in-string": "error",
  "no-unsafe-finally": "error",
  "no-unsafe-negation": "error",
  "no-loss-of-precision": "error",
  "no-useless-escape": "error",
  "no-self-assign": "error",
  "no-self-compare": "error",
  "no-throw-literal": "error",
  "no-useless-catch": "error",
  "no-useless-concat": "error",
  "no-useless-return": "error",
  "no-with": "error",
  "no-shadow-restricted-names": "error",
  "no-delete-var": "error",
  "no-label-var": "error",
  "no-global-assign": "error",
  "no-octal": "error",
  "no-fallthrough": "error",
  "no-case-declarations": "error",
  "prefer-const": "error",
};

export default tseslint.config(
  {
    ignores: [
      "node_modules/**",
      "dist/**",
      "coverage/**",
      "build/**",
      "config/**",
      "docs-site/**",
      "vite.config.ts",
      "vitest.config.ts",
    ],
  },
  {
    // Global settings — compat plugin reads settings.browsers to avoid IE-era defaults
    plugins: { compat },
    settings: {
      browsers: [
        "last 2 Chrome versions",
        "last 2 Edge versions",
        "last 2 Safari versions",
        "last 2 Firefox versions",
        "last 2 Opera versions",
        "last 2 Samsung versions",
        "last 2 ChromeAndroid versions",
        "last 2 FirefoxAndroid versions",
        "last 2 OperaMobile versions",
        "last 2 UCAndroid versions",
        "last 2 QQAndroid versions",
        "iOS >= 16.4",
        "not dead",
      ],
    },
  },
  {
    files: ["src/**/*.ts"],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    plugins: {
      "import-x": importX,
      compat,
    },
    languageOptions: {
      globals: browserGlobals,
      parserOptions: {
        project: ["./tsconfig.json", "./tsconfig.sw.json"],
        tsconfigRootDir: import.meta.dirname,
      },
    },
    // Explicit browser targets so eslint-plugin-compat never falls back to IE-era defaults
    settings: {
      browsers: [
        "last 2 Chrome versions",
        "last 2 Edge versions",
        "last 2 Safari versions",
        "last 2 Firefox versions",
        "last 2 Opera versions",
        "last 2 Samsung versions",
        "last 2 ChromeAndroid versions",
        "last 2 FirefoxAndroid versions",
        "last 2 OperaMobile versions",
        "last 2 UCAndroid versions",
        "last 2 QQAndroid versions",
        "iOS >= 16.4",
        "not dead",
      ],
    },
    rules: {
      ...sharedRules,
      // G6: import-x rules
      "import-x/no-duplicates": "error",
      "import-x/no-self-import": "error",
      "import-x/no-cycle": ["error", { maxDepth: 5 }],
      "import-x/no-useless-path-segments": ["error", { noUselessIndex: true }],
      "no-undef": "off",
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          varsIgnorePattern: "^_",
          argsIgnorePattern: "^_",
          caughtErrors: "all",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-non-null-assertion": "off", // TS strictNullChecks handles safety; ! is used for post-narrowing assertions
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-misused-promises": [
        "error",
        { checksVoidReturn: { attributes: false } },
      ],
      "@typescript-eslint/require-await": "error",
      "@typescript-eslint/consistent-type-imports": ["error", { prefer: "type-imports" }],
      "@typescript-eslint/no-unnecessary-type-assertion": "error",
      "@typescript-eslint/prefer-optional-chain": "error",
      "@typescript-eslint/no-import-type-side-effects": "error",
      "@typescript-eslint/explicit-function-return-type": "error",
      "no-console": ["error", { allow: ["warn", "error"] }],
      // Browser compat — flags APIs unsupported in our browserslist targets
      "compat/compat": "error",
    },
  },
  {
    files: ["tests/**/*.ts"],
    extends: [...tseslint.configs.recommended],
    languageOptions: {
      globals: {
        ...browserGlobals,
        vi: "readonly",
        describe: "readonly",
        it: "readonly",
        test: "readonly",
        expect: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
      },
    },
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { varsIgnorePattern: "^_", argsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-floating-promises": "off",
      "no-empty": ["error", { allowEmptyCatch: true }],
    },
  },
  {
    files: ["scripts/**/*.mjs"],
    languageOptions: {
      globals: {
        console: "readonly",
        process: "readonly",
      },
    },
    rules: {
      "no-console": "off",
    },
  },
  {
    // Cloudflare Worker — separate tsconfig, WebWorker globals
    files: ["worker/**/*.ts"],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    plugins: {
      compat,
    },
    languageOptions: {
      globals: {
        crypto: "readonly",
        URL: "readonly",
        Request: "readonly",
        Response: "readonly",
        Headers: "readonly",
        fetch: "readonly",
        console: "readonly",
      },
      parserOptions: {
        project: ["./worker/tsconfig.json"],
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      ...sharedRules,
      "no-undef": "off",
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { varsIgnorePattern: "^_", argsIgnorePattern: "^_|^err$", caughtErrorsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/consistent-type-imports": ["error", { prefer: "type-imports" }],
      "@typescript-eslint/explicit-function-return-type": "error",
      "no-console": "off",
      // Worker runs in Cloudflare V8 runtime, not a browser — skip browser-compat checks
      "compat/compat": "off",
    },
  },
);
