/**
 * AI Disclaimer Framework (S12).
 *
 * Centralised module for all AI-related disclaimers, consent tracking,
 * and disclosure banners. Every AI feature (WebLLM, NLP sentiment,
 * pattern recognition, anomaly detection) MUST route through this
 * module before rendering AI-generated content.
 *
 * Principles:
 *   1. Informed consent — user acknowledges AI limitations before use
 *   2. Persistent disclosure — visible label on every AI-generated element
 *   3. Opt-in activation — AI features default to off until user enables
 *   4. No financial advice — every AI output carries a disclaimer
 */

// ── Types ─────────────────────────────────────────────────────────────────

/** Categories of AI features that require disclaimers. */
export type AiFeatureId =
  | "webllm"
  | "nlp-sentiment"
  | "pattern-recognition"
  | "anomaly-detection"
  | "screener-dsl-translate"
  | "signal-dsl-translate"
  | "chart-explanation";

export interface AiDisclaimerConfig {
  /** Feature identifier. */
  readonly feature: AiFeatureId;
  /** Short label shown next to AI-generated content (e.g. "AI-generated"). */
  readonly badge: string;
  /** Full disclaimer text for the consent dialog. */
  readonly disclaimer: string;
  /** Whether the feature requires explicit opt-in (default: true). */
  readonly requiresOptIn: boolean;
}

export interface AiConsentState {
  /** Which features the user has acknowledged. */
  readonly acknowledged: ReadonlySet<AiFeatureId>;
  /** ISO timestamp of last acknowledgement. */
  readonly lastAcknowledgedAt: string | null;
}

// ── Default Disclaimers ───────────────────────────────────────────────────

const FINANCIAL_DISCLAIMER =
  "This output is generated by an AI model and is for informational and " +
  "educational purposes only. It does NOT constitute financial, investment, " +
  "or trading advice. Always conduct your own research and consult a " +
  "qualified financial advisor before making investment decisions.";

const AI_ACCURACY_DISCLAIMER =
  "AI models can produce inaccurate, incomplete, or misleading results. " +
  "Outputs should be verified against authoritative sources. Past patterns " +
  "do not guarantee future performance.";

export const DEFAULT_DISCLAIMERS: readonly AiDisclaimerConfig[] = [
  {
    feature: "webllm",
    badge: "AI-generated",
    disclaimer: `${FINANCIAL_DISCLAIMER}\n\n${AI_ACCURACY_DISCLAIMER}\n\nThis feature runs a local language model (Phi-4-mini) entirely in your browser via WebGPU. No data is sent to external servers.`,
    requiresOptIn: true,
  },
  {
    feature: "nlp-sentiment",
    badge: "AI sentiment",
    disclaimer: `${FINANCIAL_DISCLAIMER}\n\nNews sentiment scores are computed by a machine learning model and may not accurately reflect market conditions or the true tone of news articles.`,
    requiresOptIn: true,
  },
  {
    feature: "pattern-recognition",
    badge: "AI pattern",
    disclaimer: `${FINANCIAL_DISCLAIMER}\n\n${AI_ACCURACY_DISCLAIMER}\n\nChart pattern detection uses ONNX-based models. Detected patterns are probabilistic and should not be the sole basis for trading decisions.`,
    requiresOptIn: true,
  },
  {
    feature: "anomaly-detection",
    badge: "AI anomaly",
    disclaimer: `${FINANCIAL_DISCLAIMER}\n\nAnomaly detection highlights statistical outliers in price/volume data. Anomalies may be false positives caused by data quality issues, corporate actions, or normal market volatility.`,
    requiresOptIn: true,
  },
  {
    feature: "screener-dsl-translate",
    badge: "AI-translated",
    disclaimer: `${FINANCIAL_DISCLAIMER}\n\nThe natural language → screener DSL translation is approximate. Always review the generated expression before applying it as a filter.`,
    requiresOptIn: true,
  },
  {
    feature: "signal-dsl-translate",
    badge: "AI-translated",
    disclaimer: `${FINANCIAL_DISCLAIMER}\n\nThe natural language → signal DSL translation is approximate. Always review the generated expression before using it in alerts or strategies.`,
    requiresOptIn: true,
  },
  {
    feature: "chart-explanation",
    badge: "AI explanation",
    disclaimer: `${FINANCIAL_DISCLAIMER}\n\n${AI_ACCURACY_DISCLAIMER}\n\nChart explanations are generated by an AI model analysing visual patterns. They may miss important context or misinterpret chart formations.`,
    requiresOptIn: true,
  },
];

// ── Storage ───────────────────────────────────────────────────────────────

const STORAGE_KEY = "ct-ai-consent";

function loadConsent(): AiConsentState {
  try {
    const storage = typeof localStorage !== "undefined" ? localStorage : null;
    const raw = storage?.getItem(STORAGE_KEY) ?? null;
    if (!raw) return { acknowledged: new Set(), lastAcknowledgedAt: null };
    const parsed = JSON.parse(raw) as {
      acknowledged?: string[];
      lastAcknowledgedAt?: string;
    };
    return {
      acknowledged: new Set((parsed.acknowledged ?? []) as AiFeatureId[]),
      lastAcknowledgedAt: parsed.lastAcknowledgedAt ?? null,
    };
  } catch {
    return { acknowledged: new Set(), lastAcknowledgedAt: null };
  }
}

function saveConsent(state: AiConsentState): void {
  try {
    const storage = typeof localStorage !== "undefined" ? localStorage : null;
    storage?.setItem(
      STORAGE_KEY,
      JSON.stringify({
        acknowledged: [...state.acknowledged],
        lastAcknowledgedAt: state.lastAcknowledgedAt,
      }),
    );
  } catch {
    /* storage unavailable */
  }
}

// ── API ───────────────────────────────────────────────────────────────────

let _state: AiConsentState | null = null;

function getState(): AiConsentState {
  if (!_state) _state = loadConsent();
  return _state;
}

/** Check whether the user has acknowledged the disclaimer for a feature. */
export function hasConsent(feature: AiFeatureId): boolean {
  return getState().acknowledged.has(feature);
}

/** Record that the user has acknowledged the disclaimer for a feature. */
export function grantConsent(feature: AiFeatureId): void {
  const state = getState();
  const next: AiConsentState = {
    acknowledged: new Set([...state.acknowledged, feature]),
    lastAcknowledgedAt: new Date().toISOString(),
  };
  _state = next;
  saveConsent(next);
}

/** Revoke consent for a specific feature (opt-out). */
export function revokeConsent(feature: AiFeatureId): void {
  const state = getState();
  const ack = new Set(state.acknowledged);
  ack.delete(feature);
  const next: AiConsentState = {
    acknowledged: ack,
    lastAcknowledgedAt: state.lastAcknowledgedAt,
  };
  _state = next;
  saveConsent(next);
}

/** Revoke all AI consents. */
export function revokeAllConsent(): void {
  _state = { acknowledged: new Set(), lastAcknowledgedAt: null };
  saveConsent(_state);
}

/** Get the disclaimer config for a feature. */
export function getDisclaimer(feature: AiFeatureId): AiDisclaimerConfig {
  const found = DEFAULT_DISCLAIMERS.find((d) => d.feature === feature);
  if (!found) throw new Error(`Unknown AI feature: "${feature}"`);
  return found;
}

/** Get all feature IDs that the user has acknowledged. */
export function getAcknowledgedFeatures(): readonly AiFeatureId[] {
  return [...getState().acknowledged];
}

// ── DOM Helpers ───────────────────────────────────────────────────────────

/**
 * Create an AI badge element to attach to AI-generated content.
 * Renders as a small inline label: "⚠️ AI-generated" (or feature-specific text).
 */
export function createAiBadge(feature: AiFeatureId): HTMLElement {
  const config = getDisclaimer(feature);
  const badge = document.createElement("span");
  badge.className = "ct-ai-badge";
  badge.setAttribute("role", "status");
  badge.setAttribute("aria-label", `${config.badge} — not financial advice`);
  badge.setAttribute("title", config.disclaimer.split("\n")[0]!);
  badge.textContent = `⚠️ ${config.badge}`;
  return badge;
}

/**
 * Wrap AI-generated content in a container with a visible disclaimer badge
 * and aria attributes for screen readers.
 */
export function wrapWithDisclaimer(content: HTMLElement, feature: AiFeatureId): HTMLElement {
  const wrapper = document.createElement("div");
  wrapper.className = "ct-ai-content";
  wrapper.setAttribute("data-ai-feature", feature);
  wrapper.setAttribute("role", "region");
  wrapper.setAttribute("aria-label", `AI-generated content: ${getDisclaimer(feature).badge}`);

  wrapper.appendChild(createAiBadge(feature));
  wrapper.appendChild(content);

  return wrapper;
}

/**
 * Guard function: ensures the user has consented before running an AI feature.
 * Returns true if consent exists; otherwise returns false (caller should show dialog).
 */
export function requireConsent(feature: AiFeatureId): boolean {
  const config = getDisclaimer(feature);
  if (!config.requiresOptIn) return true;
  return hasConsent(feature);
}

/** Reset internal state (for testing). */
export function _resetForTesting(): void {
  _state = null;
}
